name: 'Comment with Benchmark Result'
# Here we define the inputs, which can be set
# from the workflow file and are consumed in our code
on: [push]
inputs:
  json_file:
    description: 'Where to find the json output of the benchmark'
    required: true
    default: 'output.json'
  comparison_json_file:
    description: 'Where to find the json output of an old benchmark for comparison. Empty for no comparison.'
    required: false
    default: ''
  token:
    description: 'GitHub token'
    default: $
    required: true
  langs:
    description: 'Project source file type'
    default: ''
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'