# Workflow to benchmark the default branch and store the results
# as an artifact.
name: Benchmark the default branch
on:
  workflow_dispatch:
    inputs:
      current_coverage:
        default: "target/scala-2.13/coverage-report/cobertura.xml"
      master_coverage:
        default: "target/scala-2.13/coverage-report/cobertura.xml"
#  pull_request_target:
  pull_request:

# A workflow consists of multiple jobs
jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Run the coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}
#          run: echo "$GITHUB_CONTEXT"

      - name: Changed files
        run: |
          git diff --name-only origin/master --output=master.diff  -- '*.scala'
        shell: bash

      - name: Generate badge
        run: |
          curl https://img.shields.io/badge/coverage-56%25-green > badge.svg
          pwd;
          ls -la
        shell: bash

#      - name: Upload changed files
#        uses: actions/upload-artifact@v2
#        with:
#          name: changed_files
#          path: master.diff
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
#          aws-region: aws-global
#
#      - name: Explore
#        run: |
#          aws help
#        shell: bash

      - name: Report
        uses: ./
        with:
          current_coverage: "target/scala-2.13/coverage-report/cobertura.xml"
          master_coverage: "target/scala-2.13/coverage-report/cobertura.xml"
          token: ${{ secrets.GITHUB_TOKEN }}
          langs: "js,ts"
