# Workflow to benchmark the default branch and store the results
# as an artifact.
name: Benchmark the default branch
on: [pull_request]

# A workflow consists of multiple jobs
jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Run the coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Changed files
        run: |
          git diff --name-only origin/master --output=master.diff  -- '*.scala'
        shell: bash

#      - name: Upload changed files
#        uses: actions/upload-artifact@v2
#        with:
#          name: changed_files
#          path: master.diff

      - name: Explore
        run: |
          aws help
        shell: bash

      - name: Report
        uses: ./
        with:
          json_file: "benchmark.json"
          comparison_json_file: "benchmark.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          langs: "js,ts"
