# Workflow to benchmark the default branch and store the results
# as an artifact.
name: Benchmark the default branch
on: [pull_request]

# A workflow consists of multiple jobs
jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Run the benchmark
    # Which themselves consist of multiple steps
    steps:
      # Each step can have a name and either references another
      # github repository (as in this case) or a docker image (not shown).
      # Please note that all references must have a version tag,
      # which forces you to pin your versions (good!)
      # The first task just clones your repository into the
      # work area of the workflow
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # Normally you would produce the benchmark output here

        # In the last task we upload the benchmark results
        # as artifacts. This will allow us to use them in a different
        # workflow later.

      - name: Upload the results
        uses: actions/upload-artifact@v2
        # this is how you pass arguments to the action,
        # in this case the arguments "name" and "path".
        # You can lookup what these arguments do
        # in the task repository:
        # https://github.com/actions/upload-artifact
        with:
          name: benchmark_results
          path: benchmark.json

      - name: Explore
        run: |
          git diff --name-only origin/master
        shell: bash

      - name: Compare JSONs
        uses: ./
        with:
          json_file: "benchmark.json"
          comparison_json_file: "benchmark.json"
          token: ${{ secrets.GITHUB_TOKEN }}
